### ISSUE TITLE
Looks awesome, but I need some help 

### ISSUE THREAD

**Issue by johntdyer** [queimadus/cover-icon-element#15]
First off this looks awesome, thank you for putting it together.   That being said I am struggling a little bit to get it working on my system..  Today I have a button card thats mostly working

```yaml
      type: custom:button-card
      template: homekit_style_settings
      entity: cover.one_car_garage_door
      label: 1 Car
      show_state: false
      show_label: true
      tap_action:
        action: call-service
        service: cover.toggle
        service_data:
          entity_id: cover.one_car_garage_door
      styles:
        icon:
          - width: 80px
          - padding-left: 0px
          - padding-right: 120px
        name:
          - justify-self: left
          - padding-left: 5px
          - padding-bottom: 10px
          - padding-top: 0px
          - padding-right: 0px
          - font-weight: bold
          - text-transform: Titlecase
          - font-size: 20px
        label:
          - font-size: 18px
          - padding-left: 5px
          - padding-bottom: 10px
          - padding-top: 20px
          - padding-right: 20px
          - justify-self: left
      state:
        - value: unavailable
          color: 'rgb(255, 0, 0)'
          icon: 'mdi:car'
          name: "???"
        - value: open
          color: 'rgb(255, 0, 0)'
          icon: 'mdi:garage-open'
          name: "Open"
        - value: closed
          color: 'rgb(121, 233, 80)'
          icon: 'mdi:garage'
          name: "Closed"
```

How would I make your card a button w/ a configurable icon ? 

Thanks
