### ISSUE TITLE
Allow specifying the Icon color

### ISSUE THREAD

**Issue by queimadus** [queimadus/cover-icon-element#9]
The element should expose an option to override the icon cover or use a CSS variable to control it so it can be overridden from outside.

[Originally requested by #7]

**Comment by tigers75** [comment]
Thanks for the fast response.
Just an idea: if I understand it correctly the fill color is a css property, and aren't therm customizable in a picture element card?
I usually use this to change an icon color:

>     elements:
>       - entity: sensor.carta
>         icon: mdi:file-document
>         style:
>           '--paper-item-icon-color': red
>           left: 5%
>           top: 67%

The HA docs state that:

> style map REQUIRED
> Position and style the element using CSS.
> 
> Default: position: absolute, transform: translate(-50%, -50%)

so maybe we can change the fill color this way?

On a side note I'd specify in the docs if the breakpoints in the array are considered < or <=

Good work anyways, I'd like I could help more.

Finally one last note: I personally would like (and seen some posts on the forum from other people too) to customize the icons used for windows and doors in HA, that especially for windows are for non european type. Customizing the icon for the object looses its link to the state of the door/window. Is it possible to do something similar to change windows and doors icons in a picture element card maintaining the open/closed state difference?

**Comment by queimadus** [comment]
> Thanks for the fast response. Just an idea: if I understand it correctly the fill color is a css property, and aren't therm customizable in a picture element card? I usually use this to change an icon color:
> 
> > ```
> > elements:
> >   - entity: sensor.carta
> >     icon: mdi:file-document
> >     style:
> >       '--paper-item-icon-color': red
> >       left: 5%
> >       top: 67%
> > ```
> 
> The HA docs state that:
> 
> > style map REQUIRED
> > Position and style the element using CSS.
> > Default: position: absolute, transform: translate(-50%, -50%)
> 
> so maybe we can change the fill color this way?

I mentioned this current limitation briefly in https://github.com/queimadus/cover-icon-element/pull/10#issue-1052652250.

Since I'm inlining the svg as an image src to re-use the inner ha-image component and to keep everything in a single file; we can't modify the CSS via the `style` properties. This is doable however, it would just require a larger set of changes that I had time for right now.  

> On a side note I'd specify in the docs if the breakpoints in the array are considered < or <=

I agree. That seems a good idea. Maybe you could send a PR with the suggested changes to the README.md? :) 

> 
> Good work anyways, I'd like I could help more.
> 
> Finally one last note: I personally would like (and seen some posts on the forum from other people too) to customize the icons used for windows and doors in HA, that especially for windows are for non european type. Customizing the icon for the object looses its link to the state of the door/window. Is it possible to do something similar to change windows and doors icons in a picture element card maintaining the open/closed state difference?

In a picture-elements card, you can actually already achieve this for entities that have a finite set of states, albeit with more boilerplate code.
For example, I customize my lights icons according to their state with something like:
```
  - entity: light.my_light
    image: /local/icons/light_bulb_off.png
    state_filter:
      unavailable: sepia(90%) hue-rotate(320deg) saturate(10)
      'off': brightness(70%) saturate(0.8)
      'on': brightness(130%) saturate(1.5) drop-shadow(0px 0px 10px gold)
    state_image:
      'on': /local/icons/light_bulb_on.png
    style:
      left: 45%
      top: 77%
      width: 7%
    tap_action:
      action: toggle
    type: image
```

You should be able to achieve a similar result for door/windows.
